<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DefaultBindingTfms)</TargetFrameworks>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ads1115/Ads1115.csproj" />
    <ProjectReference Include="../DCMotor/DCMotor.csproj" />
    <Compile Include="*.cs" />
    <None Include="README.md" />
  </ItemGroup>
</Project>